# Generated by Django 5.2.4 on 2025-07-24 17:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('books', 'Books'), ('other', 'Other'), ('sports', 'Sports'), ('clothing', 'Clothing'), ('home', 'Home & Garden'), ('electronics', 'Electronics')], default='other', max_length=50)),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.01'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('image', models.ImageField(blank=True, default='product/product.png', null=True, upload_to='product/')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='api_product_name_73c704_idx'), models.Index(fields=['price'], name='api_product_price_b6b1d7_idx'), models.Index(fields=['category'], name='api_product_categor_07b5d3_idx'), models.Index(fields=['created_at'], name='api_product_created_a91d70_idx')],
            },
        ),
    ]
